### PR TITLE
Improve header and footer

### PR DESCRIPTION
**Pull request by AlbericTrancart**
My proposition for a new header + footer:

* Moved the info text at the top to the bottom
* Removed the navlinks to only show the frontpage with stats

New "header":

image

Footer:

image

If you have suggestions...

### CODE REVIEW

**Comment by brandtamos** [comment]
This looks great! Only thing is I think we should keep the navlinks there for now. It makes it easy to pop into a recent or upcoming mission to make edits when logged in.

**Comment by AlbericTrancart** [comment]
Ok! I added a `@if (Auth::isAdmin())` condition to display the navlinks (although not tested on my local because I don't know how to create and admin account yet)

**Comment by AlbericTrancart** [comment]
Now tested with an admin account and it works!

**Comment by brandtamos** [comment]
Looks good now!

**Pull request merged**
